name: my_flutter_app
description: A sample Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # Example of a package with a caret (^) version constraint
  http: ^0.13.5 # Another package with a caret (^) version constraint
  provider: ^6.0.0 #  Example of a package with a caret (^) version constraint
  intl: 0.18.0 # Example of a fixed version constraint
  path_provider: ^2.0.0 # Example of a package with a caret (^) version constraint
  shared_preferences: ^2.0.0  # Example of a package with a caret (^) version constraint
  cached_network_image: ^3.2.0 # Example of a package with a caret (^) version constraint
  url_launcher: ^6.0.0 # Example of a package with a caret (^) version constraint
  flutter_svg: ^2.0.0 # Example of a package with a caret (^) version constraint
  json_annotation: ^4.8.1
  badges: ^3.1.2
  # Example of a package from a Git repository
  # my_custom_package:
  #   git:
  #     url: https://github.com/myusername/my_custom_package.git
  #     ref: main # Or a branch/tag name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/categories/
    - assets/dishes/
    - assets/others/
    - assets/restaurants/
